default: &default
  adapter: postgresql
  encoding: unicode
  username: el_todo_user
  password: "123456"
  host: localhost

development:
  <<: *default
  database: el_todo_development

test:
  <<: *default
  database: el_todo_test
